version = 1

[formatters.default]
class = 'logging.Formatter'
format = '%(asctime)s - %(name)s %(levelname)s: %(message)s'

[formatters.detailed]
class = 'logging.Formatter'
format = '%(asctime)s - %(name)s %(levelname)-8s %(processName)s: %(message)s'

[handlers.console]
class = 'logging.StreamHandler'
level = 'INFO'
formatter = 'default'

[handlers.file]
class = 'logging.handlers.RotatingFileHandler'
level = 'WARNING'
filename = 'log/pipeline.log'
mode = 'a'
formatter = 'detailed'
maxBytes = 1.024E6
backupCount = 5

[handlers.debug]
class = 'logging.FileHandler'
filename = 'log/debug_pipeline.log'
mode = 'w'
formatter = 'detailed'

[root]
level = 'INFO'
handlers = ['console', 'file']

